name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NPM Install
        uses: bahmutov/npm-install@v1.6.0
        with: 
          install-command: npm ci --legacy-peer-deps
      - name: Build 
        run: npm run release 
      - name: Deploy to GitHub Pages 
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh_pages 
          build_dir: dist/ng-dashboard
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}